[package]
name = "dfu-packager"
version = "0.2.1"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
byteorder = "1.5"
clap = { workspace = true }
crc32fast = "1.4"
simplelog = { workspace = true }
thiserror = { workspace = true }
