[package]
name = "dfu-packager"
version = { workspace = true }
edition = "2024"

[dependencies]
anyhow = { workspace = true }
byteorder = "1.5"
clap = { workspace = true }
crc32fast = "1.5"
simplelog = { workspace = true }
thiserror = { workspace = true }
